
version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
 
  build:
    commands:
      - echo "Build complete. Packaging for Elastic Beanstalk..."
 
  post_build:
    commands:
      - echo "Artefact ready."
 
artifacts:
  files:
    - "**/*"
  discard-paths: no